version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14
    commands:
      - npm install
      - npm install -g react-scripts
      - npm run build
    run-as: root
artifacts:
  files:
    - "**/*"
cache:
  paths:
    - "node_modules/**/*"