AWSTemplateFormatVersion: 2010-09-09
Description: login function
Transform: AWS::Serverless-2016-10-31
Resources:
  
  function:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/.
      Description: examboom login
      MemorySize: 128
      Timeout: 10
      Runtime: nodejs14.x
      Handler: index.handler
